name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.impulsiveinventories.ImpulsiveInventories
version: ${version}
api-version: 1.13

commands:
  impulsive:
    description: Main command for ImpulsiveInventories
    aliases:
      - ii
      - impinv
      - impulsiveinventories
    permission: impulsive.command

permissions:
  impulsive.command:
    description: Allows the player to use /impulsive
